name-template: '$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

exclude-labels:
  - 'skip-changelog'

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
      - 'docs/**'
      - 'wiki/**'
  - label: 'github-actions'
    files:
      - '.github/workflows/**'
  - label: 'rust'
    files:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'src/**'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'enhancement'
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'dependencies'
      - 'documentation'
      - 'rust'
      - 'github-actions'
  default: patch
