name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions: read-all

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged
    permissions:
      contents: read
    steps:
      - name: Install java
        run: |
          apk update && apk add --no-cache openjdk17-jre unzip curl

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          toolchain: stable
          components: clippy

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Build and cache Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@401fe28a8384095fc1531b9d320b292f0ee45adb # v6.7
        with:
          bundle: mimick.flatpak
          manifest-path: dev.nicx.mimick.local.yml
          cache-key: flatpak-builder-${{ hashFiles('dev.nicx.mimick.local.yml', 'Cargo.lock', 'cargo-sources.json') }}
          keep-build-dirs: true
          build-dir: flatpak_app

      - name: Run Clippy and capture JSON report
        run: flatpak-builder --run flatpak_app dev.nicx.mimick.local.yml cargo clippy --offline --all-targets --message-format=json > clippy-report.json
        continue-on-error: true

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_SCANNER_VERSION: 8.1.0.6389
        run: |
          curl -sSLo sonar-scanner.zip \
            "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}-linux-x64.zip"
          unzip -q sonar-scanner.zip
          "./sonar-scanner-${SONAR_SCANNER_VERSION}-linux-x64/bin/sonar-scanner"
